All:
	gcc AcDc.c -o AcDc
test:
	./AcDc ../test/sample1.ac out1
	./AcDc ../test/sample2.ac out2
	./AcDc ../test/sample3.ac out3
	./AcDc ../test/sample4.ac out4
	./AcDc ../test/sample5.ac out5
	./AcDc ../test/test1-variable-length.ac test1
clean:
	rm AcDc
